# Generated by Django 4.1.2 on 2023-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritika_main', '0002_post_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading_image',
            field=models.ImageField(default='default.jpg', upload_to='headings'),
        ),
    ]
