# Generated by Django 4.1.2 on 2023-01-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritika_main', '0003_post_heading_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading_image',
        ),
    ]
