# Generated by Django 4.1.2 on 2023-01-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritika_main', '0004_remove_post_heading_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading_image',
            field=models.ImageField(default='headings/default.jpg', upload_to='headings'),
        ),
    ]
