# Generated by Django 4.1.2 on 2023-01-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kritika_main', '0005_post_heading_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='headings/default.jpg', upload_to='post_images')),
                ('image_caption', models.CharField(blank=True, default='', max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kritika_main.post')),
            ],
        ),
    ]
