# Generated by Django 4.1.2 on 2023-02-18 23:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritika_main', '0006_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
