# Generated by Django 4.1.2 on 2023-02-19 00:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritika_main', '0007_alter_post_full_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
